# Makefile for SliTaz mirror.
# Check the README for more information.
#

PREFIX?=/usr

all:

install:
	install -m 0644 files/etc/lighttpd/vhosts.conf /etc/lighttpd

uninstall:
	rm -f /etc/lighttpd/vhosts.conf
