#!/bin/sh
#
# Main SliTaz Mirror admin utility
#
# Copyright (C) 2012 SliTaz GNU/Linux - BSD License
#
# Authors : Christophe Lincoln <pankso@slitaz.org>
#

REPOS="/home/slitaz/repos"
WWW="/var/www"
MIRROR="$WWW/mirror"
INFO="$WWW/mirror-info"
TINY="$WWW/pizza/tiny"
BACKUPS="/home/backups"

usage() {
	cat << EOT

Usage: $(basename $0) [command]
Commands:
  up-info       Update mirror.slitaz.org/info/ web interface
  up-tiny       Update tiny.slitaz.org/ web interface
  up-mirror     Update mirror.slitaz.org files
  up-pkgs       Update pkgs.slitaz.org

EOT
}

case "$1" in
	up-info)
		echo "Updating: mirror.slitaz.org/info..."
		cd $REPOS/slitaz-forge && hg pull -u
		echo "Copying info to: $INFO"
		cp -a mirror/info/* $INFO ;;
	up-tiny)
		echo "Updating: tiny.slitaz.org..."
		cd $REPOS/tiny-slitaz && hg pull -u
		echo "Copying tiny to: $TINY"
		cp -a * $TINY ;;
	up-mirror)
		echo "Updating: mirror.slitaz.org files..." 
		cd $REPOS/slitaz-forge && hg pull -u
		echo "Copying root to: $MIRROR"
		cp -a mirror/root/* $MIRROR ;;
	up-pkgs)
		echo "Updating: pkgs.slitaz.org..."
		cd $REPOS/slitaz-forge && hg pull -u
		echo "Copying pkgs to: $WWW/pkgs"
		cp -a pkgs/*.* $WWW/pkgs 
		cp -a pkgs/lib $WWW/pkgs 
		cd pkgs && make install-msg ;;
	*)
		usage ;;
esac
exit 0
