#!/bin/sh
#
# Main SliTaz Mirror admin utility
#
# Copyright (C) 2012 SliTaz GNU/Linux - BSD License
#
# Authors : Christophe Lincoln <pankso@slitaz.org>
#

REPOS="/home/slitaz/repos"
WWW="/var/www"
VHOST="$WWW/mirror"
INFO="$WWW/mirror-info"
TINY="$WWW/pizza/tiny"
BACKUPS="/home/backups"

usage() {
	cat << EOT

Usage: $(basename $0) [command]
Commands:
  up-info       Update mirror.slitaz.org/info/ web interface
  up-tiny       Update tiny.slitaz.org/ web interface
  up-mf         Update mf.slitaz.org web interface

EOT
}

case "$1" in
	up-info)
		echo "Updating: mirror.slitaz.org/info..."
		cd $REPOS/slitaz-forge && hg pull -u 
		cp -a mirror/info/* $INFO ;;
	up-tiny)
		echo "Updating: tiny.slitaz.org..."
		cd $REPOS/slitaz-pizza && hg pull -u 
		cp -a php/tiny/* $TINY 
	up-mf)
		echo "Updating: mf.slitaz.org..." 
		cd $REPOS/slitaz-forge && hg pull -u ;;
	*)
		usage ;;
esac
exit 0
