#!/bin/sh

read32()
{
	echo $(od -j $((0x$1)) -N 4 -t u4 -An kernel)
}

ddsect()
{
	dd bs=512 count=$@ 2> /dev/null
}

case "$1" in
extract)
	ddsect 2 > kernel
	setupsz=$(($(read32 1F1) & 255))
	ddsect $(($setupsz - 1)) >> kernel
	[ $(read32 228) -ne 0 ] &&
	ddsect 1 | strings > cmdline
	syssz=$(read32 1F4)
	syssz=$(( ($syssz + 31) / 32 ))
	ddsect $syssz >> kernel
	ramsz=$(read32 21C)
	ddsect $((($ramsz + 511) / 512)) of=rootfs
	dd bs=1 seek=$ramsz count=0 of=rootfs 2> /dev/null
	;;
*)	cat <<EOT
usage: 
# cat fd0*.img | $0 extract
	creates kernel, rootfs and cmdline files
# cat fd1*.img | unlzma | cpio -i
# cat fd2*.img | unlzma | cpio -i
...
EOT
esac
