#!/bin/sh
#
# Pangolin admin utility
#
# Copyright (C) 2012-2017 SliTaz GNU/Linux - BSD License
# Authors : Christophe Lincoln <pankso@slitaz.org>
#

REPOS="/home/slitaz/repos"
WWW="/home/vhost"
WEBSITE="$WWW/www.slitaz.org/website"
PYTHON_LIB="/usr/lib/python2.7"
HGUSERS="/home/slitaz/auth/hgusers"

usage() {
	cat << EOT

Usage: $(basename $0) [command]

Commands:
  up-www       Update website www.slitaz.org
  up-forum     Update forum.slitaz.org theme
  up-doc       Update doc.slitaz.org theme and configs
  up-hg        Update Hg web interface hg.slitaz.org
  up-pizza     Update Pizza web interface pizza.slitaz.me
  up-play      Update Gamers web interface play.slitaz.me
  up-pangolin  Update pangolin.slitaz.org virtual host
  adduser      Add a new user to Hg
  stats        Display some server stats

EOT
}

# While libtaz.sh is not installed on Pangolin
#
newline() {
	echo ""
}

boldify() {
	echo -e "\\033[1m$@\\033[0m"
}

separator() {
	echo "================================================================================"
}

#
# handle commands
#

case "$1" in

	up-www)
		# Update website from repo.
		newline
		boldify "Updating: www.slitaz.org..."
		cd ${WEBSITE} && hg pull -u 
		newline ;;
	
	up-forum)
		# Update forum.slitaz.org theme
		newline
		boldify "Updating: forum.slitaz.org..."
		cd ${REPOS}/slitaz-forge && hg up
		cp -a forum/my-templates ${WWW}/forum.slitaz.org/public_html 
		newline ;;
	
	up-doc)
		# Update doc.slitaz.org theme
		newline
		boldify "Updating: doc.slitaz.org..."
		cd ${REPOS}/slitaz-forge && hg up
		cp -a doc/* ${WWW}/doc.slitaz.org/public_html
		chown www.www ${WWW}/doc.slitaz.org/public_html/conf
		chown www.www ${WWW}/doc.slitaz.org/public_html/conf/local.php
		newline ;;
	
	up-hg)
		# Update hg.slitaz.org template
		newline
		boldify "Updating Mercurial template..."
		cd ${REPOS}/slitaz-dev-tools && hg update 
		cp -a slitaz-mercurial-style/* ${PYTHON_LIB}/site-packages/mercurial
		chown -R root.root ${PYTHON_LIB}/site-packages/mercurial/templates
		newline ;;
		
	up-pizza)
		# Update pizza.slitaz.me
		newline
		boldify "Updating Pizza builder..."
		cd ${REPOS}/slitaz-pizza && hg update
		cp /etc/slitaz/pizza.conf /etc/slitaz/pizza.conf.bak
		make install; cd ..
		cp -f /etc/slitaz/pizza.conf.bak /etc/slitaz/pizza.conf
		pizza up-files
		newline ;;
	
	up-play)
		# Update play.slitaz.me
		newline
		boldify "Updating play.slitaz.org..."
		cd ${REPOS}/slitaz-forge && hg update
		cp -rf play.slitaz.me/* ${WWW}/play.slitaz.me/public_html
		# Tazcraft
		cd ${REPOS}/slitaz-dev-tools && hg update
		rm -rf ${WWW}/play.slitaz.me/public_html/tazcraft
		cp -rf tazcraft/cgi-bin ${WWW}/play.slitaz.me/public_html/tazcraft
		newline ;;
	
	up-pangolin)
		# Update pangolin.slitaz.org and tools
		newline
		boldify "Updating tool: pangolin"
		cd ${REPOS}/slitaz-forge/pangolin && hg up
		make install
		
		newline
		boldify "Updating tool: slitaz-release"
		cd ${REPOS}/slitaz-dev-tools/slitaz-release && hg up
		make install
		
		newline
		boldify "Updating: pangolin.slitaz.org..."
		cd ${REPOS}/slitaz-forge && hg up
		cp -a pangolin/web/* ${WWW}/pangolin.slitaz.org/public_html
		newline ;;
	
	adduser)
		[ ! "$2" ] && echo "Missing user name arg" && exit 0
		[ ! "$3" ] && echo "Missing password arg" && exit 0
		htpasswd -b ${HGUSERS} "$2" "$3" ;;
	
	stats)
		# Echo some stats.
		newline
		boldify "Memory usage"
		separator
		free -m | grep ^Mem
		newline
		boldify "Connected users"
		separator
		who 
		newline
		boldify "HG users"
		cat ${HGUSERS} | wc -l ;;
	
	*)
		usage ;;
esac
exit 0
