#!/bin/sh
#
# Tank - Admin Tank, backup, update and give stats.
#
# (C) 2011 SliTaz - GNU General Public License.
# Author: Christophe Lincoln <pankso@slitaz.org>
#

REPOS="/home/slitaz/repos"
WWW="/home/slitaz/www"
VHOST="$WWW/tank"
WEBSITE="$WWW/website"
BACKUPS="/home/backups"

usage() {
	cat << EOT

Usage: $(basename $0) [command]
Commands:
  backup|-b    Backup files and MySQL DB
  adduser      Add user on Tank and create people files
  up-stats     Update Awstats statistics (run by cron)
  
  up-tank      Update http://tank.slitaz.org/
  up-people    Update http://people.slitaz.org/
  up-pro       Update http://pro.slitaz.org/
  up-boot      Update http://boot.slitaz.org/
  up-cook      Update http://cook.slitaz.org/

EOT
}

case "$1" in
	backup|-b)
		# Backup config files and SQL db.
		echo "TODO" ;;
	up-tank)
		# Update Tank web interface: http://tank.slitaz.org/
		echo -e "\nUpdating: tank.slitaz.org..."
		cd $REPOS/slitaz-forge
		[ "$2" == "--nohg" ] || hg pull -u
		rm -rf $VHOST/*.* $VHOST/images
		cp -a tank/web/* $VHOST 
		echo "" ;;
	up-people)
		# Update People web interface: http://people.slitaz.org/
		echo -e "\nUpdating: people.slitaz.org..."
		cd $REPOS/slitaz-forge
		[ "$2" == "--nohg" ] || hg pull -u
		rm -rf $WWW/people/*
		cp -a people/* $WWW/people 
		echo "" ;;
	up-pro)
		# Update Pro website: http://pro.slitaz.org/
		echo -e "\nUpdating: pro.slitaz.org..."
		cd $REPOS/slitaz-forge
		[ "$2" == "--nohg" ] || hg pull -u
		rm -rf $WWW/pro/*
		cp -a pro/* $WWW/pro
		echo "" ;;
	up-boot)
		# Update Web Boot interface: http://boot.slitaz.org/
		echo -e "\nUpdating: boot.slitaz.org..."
		cd $REPOS/slitaz-forge
		[ "$2" == "--nohg" ] || hg pull -u
		rm -rf $WWW/boot/*
		cp -a boot/* $WWW/boot 
		echo "" ;;
	up-cook)
		# Update Web Boot interface: http://boot.slitaz.org/
		echo -e "\nUpdating: cook.slitaz.org..."
		cd $REPOS/slitaz-forge
		[ "$2" == "--nohg" ] || hg pull -u
		cp -a cook/* $WWW/cook
		cp -a cook/* $WWW/cook/undigest
		echo "" ;;
	up-stats)
		echo -e "\nUpdating all awstats databases..."
		for vh in pro boot cook people
		do
			/var/www/cgi-bin/awstats.pl -config=$vh.slitaz.org -update
		done
		echo "" ;;
	adduser)
		# On Tank /etc/skel is empty to let tank handle default user
		# files.
		echo ""
		if [ -n "$2" ]; then
			user=$2
		else
			echo -n "User name: " && read user
		fi
		if [ -d /home/$user ]; then
			echo -e "User $user already exists...\n" && exit 1
		fi
		echo "Adding user: $user"
		# adduser -s /bin/sh -g "SliTaz User" -G users -h /home/$user $user # for cooking
		adduser $user
		# HG access
		echo -n "Hg password: " && read passwd
		echo "$user:$passwd" >> /etc/lighttpd/plain.passwd
		# Public dir at http://people.slitaz.org/~$user/
		cp -a /usr/share/tank/Public/* /home/$user/Public
		sed -i s/'%user%'/"$user"/ /home/$user/Public/index.html
		# README and empty Shell profile
		cp -a /usr/share/tank/README /home/$user/
		cat > /home/$user/.profile << EOF
# ~/.profile: Executed by Bourne-compatible login SHells.
#
EOF
		chown -R $user.$user /home/$user
		echo -e "Done\n" ;;
	*)
		usage ;;
esac
exit 0
