<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: pankso
 * Date: Fri, 05 Aug 2011 16:48:26 +0000
 */

$conf['title'] = 'SliTaz Doc';
$conf['template'] = 'slitaz-orange';
$conf['license'] = 'gnufdl';
$conf['tocminheads'] = '4';
$conf['maxtoclevel'] = '2';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['subscribers'] = 1;
$conf['userewrite'] = '1';
$conf['sepchar'] = '-';
$conf['mailfrom'] = 'devel@slitaz.org';
$conf['rss_type'] = 'rss2';
$conf['rss_linkto'] = 'rev';
$conf['recent_days'] = 5;
$conf['plugin']['captcha']['mode'] = 'text';
$conf['plugin']['translation']['translations'] = 'cn de en es fr id it pt ro ru';
$conf['plugin']['translation']['checkage'] = 1;

// end auto-generated content
