# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: localhost 
    port: 25
    domain: slitaz.org
#    authentication: :login
#    user_name: pankso@slitaz.org
#    passwor: ********
